image: registry.gitlab.com/calyxos/ci-images-fdroid-repo:latest

variables:
  LC_ALL: "C.UTF-8"

before_script:
  - echo $fdroid_keystore_base64 | base64 -d >keystore.jks
  - chmod 600 config.yml keystore.jks
  - mkdir -p fdroid/repo
  - git clone https://gitlab.com/fdroid/fdroidserver
  # Use newer version for https://gitlab.com/fdroid/fdroidserver/-/commit/1bb963d7682485ba9cfeeb7eb049a053feb10c3c
  - git -C fdroidserver checkout b54eb946f19ca0c4bf2c681715716b3355ea5b17
  # Temporary fdroidserver patch to not make it barf Makefiles
  - git -C fdroidserver apply ../0001-TEMPORARY-Revert-hashing-of-graphics-filename.patch

fdroid-repo:
  stage: deploy
  script:
  - (cd fdroid/repo && while read -r line || [ -n "$line" ]; do rm -f $line; done < ../../cleanup.txt)
  - ./download.py
  - cd fdroid
  - echo keypass:' '$fdroid_keypass >>config.yml
  - echo keystorepass:' '$fdroid_keystorepass >>config.yml
  - ../fdroidserver/fdroid update --pretty
  - rm -rf archive
  - mkdir /fdroid && ../fdroidserver/fdroid deploy
  - rm -rf /fdroid/archive
  - cd .. && mkdir public && mv -v /fdroid public
  artifacts:
    paths:
    - public
    expire_in: 1 week
  only:
  - main
  - schedules
  cache:
    paths:
    - cache
    - fdroid/repo/*.apk
