image: registry.gitlab.com/calyxos/ci-images-fdroid-repo:latest

variables:
  LC_ALL: "C.UTF-8"

before_script:
  - echo $fdroid_keystore_base64 | base64 -d >keystore.jks
  - chmod 600 fdroid/config.py keystore.jks
  - mkdir -p fdroid/repo
  # Temporary fdroidserver patch to not make it barf Makefiles
  - git clone https://gitlab.com/fdroid/fdroidserver -b 2.0
  - git -C fdroidserver apply ../0001-TEMPORARY-Revert-hashing-of-graphics-filename.patch

fdroid-repo:
  stage: deploy
  script:
  - (cd fdroid/repo && while read -r line || [ -n "$line" ]; do rm -f $line; done < ../../cleanup.txt)
  - ./download.py
  - cd fdroid
  - echo "keypass=\"$fdroid_keypass\"" >>config.py
  - echo "keystorepass=\"$fdroid_keystorepass\"" >>config.py
  - ../fdroidserver/fdroid update --pretty
  - rm -rf archive
  - mkdir /fdroid && ../fdroidserver/fdroid deploy
  - rm -rf /fdroid/archive
  - cd .. && mkdir public && mv -v /fdroid public
  artifacts:
    paths:
    - public
    expire_in: 1 week
  only:
  - main
  - schedules
  cache:
    paths:
    - cache
    - fdroid/repo/*.apk
